### PR TITLE
Implement CI/CD using Github Actions

### PR DESCRIPTION
**Pull request by mo3rfan**
Had to fix the `backend` Dockerfile and helper scripts to ensure the tests run. However the unit tests had some failure that I didn't check further.

To check the github actions runs, you can find it on my fork: https://github.com/mo3rfan/digital-twin-toolbox/actions

Ref: https://github.com/geosolutions-it/digital-twin-toolbox/issues/33

### CODE REVIEW

**Comment by tdipisa** [comment]
> However the unit tests had some failure that I didn't check further.
This part if for you to review, I guess.

**Comment by allyoucanmap** [comment]
@tdipisa @mo3rfan now there is another problem but it does not seems related to tests, it's saying `no space left on device`

https://github.com/mo3rfan/digital-twin-toolbox/actions/runs/11251898787

**Comment by mo3rfan** [comment]
Tests are working now: https://github.com/mo3rfan/digital-twin-toolbox/actions/runs/11253236378/job/31292329536
Thanks for the fix @allyoucanmap 

Few things I need to do two things before we merge this:

- [ ] Move the github custom runner to this repository.
- [ ] Set the dockerhub credentials to this repository.

**Comment by mo3rfan** [comment]
I don't think I have the credentials or permission to get the geosolutions dockerhub tokens. @tdipisa or @randomorder We need to add two repository secrets [here](https://github.com/geosolutions-it/digital-twin-toolbox/settings/secrets/actions):
- `DOCKERHUB_USERNAME` 
- `DOCKERHUB_TOKEN`

This token should have permission to push to both:

- https://hub.docker.com/repository/docker/geosolutionsit/digital-twin-toolbox-backend
- https://hub.docker.com/repository/docker/geosolutionsit/digital-twin-toolbox-frontend

Eitherway, we can merge this PR now. The deployment job that will fail can be re-run at anytime after the above token is set.

**Comment by tdipisa** [comment]
> @tdipisa or @randomorder We need to add two repository secrets [here](https://github.com/geosolutions-it/digital-twin-toolbox/settings/secrets/actions):

That's for you @randomorder

**Comment by randomorder** [comment]
> > @tdipisa or @randomorder We need to add two repository secrets [here](https://github.com/geosolutions-it/digital-twin-toolbox/settings/secrets/actions):
> 
> That's for you @randomorder

Secrets are in place. Go ahead and test it again please @mo3rfan before merging

**Comment by mo3rfan** [comment]
@allyoucanmap  The latest version of micromamba has [broken](https://github.com/mo3rfan/digital-twin-toolbox/actions/runs/11440460851/job/31826436371#step:5:558) the build again.

Breaking change: https://mamba.readthedocs.io/en/latest/developer_zone/changes-2.0.html#micromamba

It's best to pin the version of micromamba in the backend's `Dockerfile`.

**Comment by allyoucanmap** [comment]
@mo3rfan but it should be already forced to the version 1.5.10 https://github.com/geosolutions-it/digital-twin-toolbox/blob/main/backend/Dockerfile#L28. Is the branch aligned to main?

**Comment by mo3rfan** [comment]
> @mo3rfan but it should be already forced to the version 1.5.10 https://github.com/geosolutions-it/digital-twin-toolbox/blob/main/backend/Dockerfile#L28. Is the branch aligned to main?

Thanks for pointing out, I will rebase over those changes.

**Comment by mo3rfan** [comment]
Builds are functional: https://github.com/geosolutions-it/digital-twin-toolbox/actions/runs/11441453209/job/31831496187?pr=41

Tested docker login: https://github.com/mo3rfan/digital-twin-toolbox/actions/runs/11441036990/job/31829327202#step:2:9

Also [increased](https://docs.google.com/document/d/1uj9Rbk0g-3D9lMRfWlbGRtTd6zXcUOkCqHhihYDIfto/edit?tab=t.0#heading=h.ksnsn6s3ev4h) the space under `/var` logical volume on self-hosted runner so we don't encounter more space issues with builds on docker.

**Review by allyoucanmap — APPROVED** [review]

**Pull request merged**
